name: CICD EXAMPLE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3 # Change to your desired Go version

    - name: Build binary
      run: |
        go build -o main
      working-directory: ${{ github.workspace }}

    - name: Execute binary
      run: |
        ./main
      working-directory: ${{ github.workspace }}
          

